@startuml
'https://plantuml.com/activity-diagram-beta

sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}

start
:User enters "addbystep";
repeat :User enters name;
  :process name;
repeat while (Name is valid?) is (no)
repeat :User enters number;
  :process number;
repeat while (Number is valid?) is (no)
repeat :User enters email;
  :process email;
repeat while (Email is valid?) is (no)
repeat :User enters address;
  :process address;
repeat while (address are valid?) is (no)
:display the end message;

repeat :User interacts with GUI <$rake>;;

repeat while (Does the user close the GUI?) is (no)



stop


@enduml
