@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CopyCommandParser" as CopyCommandParser LOGIC_COLOR
participant "<<class>>\nParerUtil" as ParserUtil LOGIC_COLOR
participant "command:CopyCommand" as CopyCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("copy 1 name email")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("copy 1 name email")
activate AddressBookParser

create CopyCommandParser
AddressBookParser -> CopyCommandParser
activate CopyCommandParser

CopyCommandParser --> AddressBookParser
deactivate CopyCommandParser

AddressBookParser -> CopyCommandParser : parse("1 name email")
activate CopyCommandParser

CopyCommandParser -> ParserUtil : parseFieldsToCopy("name email")
activate ParserUtil

ParserUtil --> CopyCommandParser
deactivate ParserUtil


create CopyCommand
CopyCommandParser -> CopyCommand
activate CopyCommand

CopyCommand --> CopyCommandParser : command
deactivate CopyCommand

CopyCommandParser --> AddressBookParser : command
deactivate CopyCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
CopyCommandParser -[hidden]-> AddressBookParser
destroy CopyCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> CopyCommand : execute(m)
activate CopyCommand

CopyCommand -> Model : getPerson(1)
activate Model

Model --> CopyCommand
deactivate Model

CopyCommand -> CopyCommand : getInfo()

create CommandResult
CopyCommand -> CommandResult
activate CommandResult

CommandResult --> CopyCommand
deactivate CommandResult

CopyCommand --> LogicManager : result
deactivate CopyCommand

[<--LogicManager
deactivate LogicManager
@enduml
